### ISSUE TITLE
how to get the text of editable node

### ISSUE THREAD

**Issue by ghost** [nicolaserny/react-gojs-example#3]
use react-gojs and redux, when I add a node and change the node text, but I don't know how to get the editable node text

**Comment by nicolaserny** [comment]
Sorry for my late answer. I will do a small example as soon as possible

**Comment by nicolaserny** [comment]
I have just updated the example to support text editing.

Main steps:
- Make your nodes editable:
```javascript
            $(go.TextBlock, { margin: 8, editable: true }, new go.Binding('text', 'label'))
```
- Listen to TextEdited gojs events:
```javascript
TextEdited: this.onTextEdited
```
- In onTextEdited, dispatch a redux action to update the state (model)
